services:
  file-storing-service:
    build:
      context: ../file-storing-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=antiplagiat
      - DB_SSLMODE=disable

  file-analysis-service:
    build:
      context: ../file-analysis-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=antiplagiat
      - DB_SSLMODE=disable

  postgres:
    image: postgres:15-alpine
    container_name: antiplagiat_db
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: antiplagiat
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d antiplagiat"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
